language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz python-tk python-matplotlib
install:
  - travis_retry pip install Sphinx
  - travis_retry pip install recommonmark
  - travis_retry pip install pep8
  - travis_retry pip install coverage
  - travis_retry pip install coveralls
  - travis_retry pip install numpy
script:
  - python -Wall setup.py try
  - python setup.py install
  - python -Wall setup.py test
  - COVERAGE=1 coverage run test/runtest.py
  - python run.py --doctest
  - python run.py --html
after_script:
  - pep8 --exclude=asizeof.py,metadata.py,bottle*.py --max-line-length=80 pympler
after_success:
  - coveralls
